### ISSUE TITLE
add movies as collections

### ISSUE THREAD

**Issue by CuddleBear92** [Darklyter/StashPlexAgent.bundle#1]
would be great if we could get movie collections added for easier grouping.

**Comment by Darklyter** [comment]
It already creates collections based on the site, which you could always set a "site" to be a movie name if you wanted.  Stash really doesn't support "Movies" very well, so I'll admit that I haven't looked into them too much.  Are you talking about from Stash or from a secondary source?

**Comment by Darklyter** [comment]
Ok, it's in there with customizable prefix
