### ISSUE TITLE
Pull sites, studio and tag images to use in collections

### ISSUE THREAD

**Issue by CuddleBear92** [Darklyter/StashPlexAgent.bundle#11]
Sites, studios and tag images should be pulled and used if not empty.

**Comment by Darklyter** [comment]
Oh, for the collections?  Hmmm...  haven't looked into pictures for the collections, but I'll see if I can affect that

**Comment by Darklyter** [comment]
Well, bad news.  I can't find anything about affecting anything other than the name of the collection from a plugin.  I'll revisit this if I find something workable though.  Sorry
