### ISSUE TITLE
Pull and use Site and Studio desciptions

### ISSUE THREAD

**Issue by CuddleBear92** [Darklyter/StashPlexAgent.bundle#12]
Site and Studio descriptions should be pulled and used for a full sync.

**Comment by Darklyter** [comment]
You're a pain in my butt.
I'll take a look.  :-P

**Comment by Darklyter** [comment]
(That was a joke btw, it's been a long day at work)

**Comment by Darklyter** [comment]
Well, bad news.  I can't find anything about affecting anything other than the name of the collection from a plugin.  I'll revisit this if I find something workable though.  Sorry
