### ISSUE TITLE
Ratings doesn't support the new Stash Rating system

### ISSUE THREAD

**Issue by Tscherno** [Darklyter/StashPlexAgent.bundle#23]
Since Stash changed to the new configurable rating system, a 4 star rating in Stash results to 1600% in Plex for example.

**Comment by electblake** [comment]
addressed in a PR (as part of stash to plex user ratings sync)

https://github.com/Darklyter/StashPlexAgent.bundle/pull/21#discussion_r1105280806

**Comment by Darklyter** [comment]
And merged in
