### ISSUE TITLE
ratings is not being saved correctly anymore

### ISSUE THREAD

**Issue by CuddleBear92** [Darklyter/StashPlexAgent.bundle#25]
the rating system has changed somehow, it no longer does the ratings correctly. a 5 star in stash is now 2000% in plex, the value seems to have changed.

**Comment by Darklyter** [comment]
Are you up to date on both?  I was just modifying that the other day and it's working fine for me

**Comment by Darklyter** [comment]
Stash did a change with v22.1 I think that had to be fixed

**Comment by CuddleBear92** [comment]
closing this since its fixed
