### ISSUE TITLE
option to prefix whatever you want to a collection sort order

### ISSUE THREAD

**Issue by CuddleBear92** [Darklyter/StashPlexAgent.bundle#3]
option to prefix whatever you want to a collection sort order.
allowing for example to set `00 - ` as a prefix for studios or `01 - ` for movie collections so studios is always sorted over movies.
this will work great with #1 and #2

**Comment by Darklyter** [comment]
Ok, I just added a small tweak to allow you to define the Site/Studio collection name prefixes. 
They default to "Site: " and "Studio: ", but can be changed to whatever
