### ISSUE TITLE
Metadata import/update to Plex does not work anymore (after update to V24)

### ISSUE THREAD

**Issue by andiiis5** [Darklyter/StashPlexAgent.bundle#32]
Everything worked fine until the upgrade to V24, now metadata does not get fetched or updated anymore.
does anymode else have this issue?

**Comment by Tscherno** [comment]
0.24 changed a lot of stuff for plugins. You have to update to the latest version of the plugin.

**Comment by andiiis5** [comment]
I downloaded the latest version here and deleted the old plex plugin... still no difference

**Comment by Tscherno** [comment]
Hmh works for me. Probably stupid question: did you restart plex afterwards?

**Comment by andiiis5** [comment]
Yes, but at least good to hear that it still works and only I have this problem. Probably I try reinstalling stash...
Thx
Am 12. Jan. 2024, 21:47 +0100 schrieb Tscherno ***@***.***>:

**Comment by trek-e** [comment]
if it helps any I had to re-tweak the settings to get it to work properly like I wanted again.

**Comment by Tscherno** [comment]
You could check the logs as well. On plex and on stash.

**Comment by andiiis5** [comment]
Jan 12, 2024 23:24:13.463 [31212] Fehler — [Req#bd5c] Error parsing content.
Jan 12, 2024 23:24:13.463 [31212] Fehler — [Req#bd5c] Exception caught while attempting to match metadata on item 23331: Error parsing file

this could be it... I get this while matching any file... and exact those files worked before.

**Comment by Tscherno** [comment]
Try again with the attached version please. Thats the one i currently successfully use.

[StashPlexAgent.bundle.zip](https://github.com/Darklyter/StashPlexAgent.bundle/files/13924947/StashPlexAgent.bundle.zip)

**Comment by andiiis5** [comment]
Thx alot. Did not work at once and was the same I used. 
Anyways.. I reinstalled stash and set it up from scratch using my db-backup... now it works again.
Thx again for your tips and quick response.

**Comment by Tscherno** [comment]
You could close the issue.
