### ISSUE TITLE
Poster Enchantment

### ISSUE THREAD

**Issue by XCoolBeatX** [Darklyter/StashPlexAgent.bundle#33]
Hi All,

It would be a cool feature if the studio banner (logo) is displayed on the bottom right of the media poster. This is something that [PornDB's Plex Plugin](https://github.com/ThePornDatabase/ThePornDB.bundle) does and it would be cool to have the same with the Stash plugin.

Example Of the PornDb one:

![image](https://github.com/Darklyter/StashPlexAgent.bundle/assets/51534776/3fdfdb55-e7d5-4bf2-8560-7d145ba9dd62)

**Comment by Darklyter** [comment]
That's a function of TPDB, not the plugin.  The Stash plugin just takes what Stash hands it, so you would need for it to be branded within Stash itself, I'm afraid.
