### ISSUE TITLE
an option to only match with certain requirements

### ISSUE THREAD

**Issue by CuddleBear92** [Darklyter/StashPlexAgent.bundle#4]
an option to only match with certain requirements, for example only match if a stashdb id is present. 
workaround would be to use genre or labels for both or either states. having a sorted or unsorted state. this might work better for labels than genres.

**Comment by Darklyter** [comment]
Hmm...  would need to hard code this one into the Prefs.  "Only if StashID is Present" should be pretty easy, just a checkbox selection.  However for genre/labels would be trickier.  What sort of thing are you envisioning, an example if you could.

**Comment by CuddleBear92** [comment]
been thinking about this a bit more, an option for StashDB ID and URL's would make sense for some users i believe.

**Comment by Darklyter** [comment]
Ok, this one's done...  I also put in a check for "Organized" for good measure.  ;-)
