### ISSUE TITLE
pull personal ratings and append as plex rating

### ISSUE THREAD

**Issue by CuddleBear92** [Darklyter/StashPlexAgent.bundle#5]
pull personal ratings and append as plex rating to make that feature seamless

**Comment by Darklyter** [comment]
It should already be pulling the Stash star rating, then multiplying by 2 to get the Plex 0-10 instead of Stash 0-5.  If that's not the case for you let me know

**Comment by CuddleBear92** [comment]
was talking about the scene ratings. not even sure if you can change those with an agent at all.

**Comment by Darklyter** [comment]
I don't know what you mean, I'm afraid.  The only rating I know of in Plex is the Star rating, which should be getting set already

**Comment by CuddleBear92** [comment]
oh it does add to the rating. it just didnt add to the 5 step stars on the movies in plex cause thats the personal shit. i see i see, my mistake!
