### ISSUE TITLE
option to pull performer tags and apply to scenes

### ISSUE THREAD

**Issue by CuddleBear92** [Darklyter/StashPlexAgent.bundle#7]
an option to pull performer tags from each performer and append to the scene would be great. you could also re-use the tag blacklist you already have in place aswell for that feature. could have some great interactions!

**Comment by Darklyter** [comment]
Ok, this is a good idea.  Pull the tags from the actors, append the list to the scene tags, and throw away duplicates...  This one shouldn't be too bad

**Comment by CuddleBear92** [comment]
good to hear! even if stash doesnt want this feature, it does become quite useful imo

**Comment by Darklyter** [comment]
Ok, it's in with the new commit.  👍
